/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
    	roleMaintenance(controller: "role", action: "(create|edit|save|update|delete)") {
    	    before = {
    	        accessControl {
    	            role("Administrator")
    	        }
    	    }
    	}
    	accountMaintenance(controller: "account", action: "(edit|update)") {
    	    before = {
    	        accessControl {
    	            role("ROLE_ADMIN")
    	            role("ROLE_PAYING_MEMBER")
    	            role("ROLE_NON_PAYING_MEMBER")
    	        }
    	    }
    	}
    	adminAccountMaintenance(controller: "account", action: "delete") {
    	    before = {
    	        accessControl {
    	            role("ROLE_ADMIN")
    	        }
    	    }
    	}
    }
}
