/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
    	roleMaintenance(controller: "role", action: "(create|edit|save|update|delete)") {
    	    before = {
    	        accessControl {
    	            role("ROLE_ADMIN")
    	        }
    	    }
    	}
    	accountMaintenance(controller: "account", action: "(delete|save|create|list)") {
    	    before = {
    	        accessControl {
    	            role("ROLE_ADMIN")
    	        }
    	    }
    	}
	    virtueEntryMaintenance(controller: "virtueEntry", action: "(create|edit|save|update|delete|newEntry)") {
	        before = {
	            accessControl {
    	            role("ROLE_SIMPLE_USER")
	            }
	        }
	    }
    }
}
